pipeline {
    agent {
        node {
            label 'maven-agent'
        }
    }

environment {
    PATH = "/opt/apache-maven-3.9.1/bin:$PATH"
}
    stages {
         stage('Clone code') {
             steps {
                script {
                    sh '''
                    git clone --no-checkout https://github.com/hossam141/tweet-trend-devops.git
                    cd tweet-trend-devops
                    git config core.sparseCheckout true
                    echo "tweet-trend-app/*" > .git/info/sparse-checkout
                    git checkout main
                    '''
                }
             }
         }
        stage('build'){
            steps {
                sh 'mvn clean deploy'
            }
        }
        stage('SonarQube analysis') {
            environment {
            scannerHome = tool 'Valaxy-SonarScanner'
            }
        steps { 
        withSonarQubeEnv('Valaxy-SonarQube-Server') {
            sh "${scannerHome}/bin/sonar-scanner"
    }
  }
    }
}
}