apiVersion: v1
kind: Secret
metadata:
  name: cred
  namespace: valaxy
data:
  .dockerconfigjson: rhknnflIJDBIjogewoJCSJ2ZDFFiMNDkwNS5qZnJvZy5pbyI6IHsKCQkJImF1dGgiOiAiYkc5BiMkYzYzBCbmJXRnBiQzVqYjIwNlZtRnNZWGg1UURFeU13PT0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson